# Generated by Django 3.0 on 2020-01-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='新曲名を追加してください', max_length=50)),
                ('level', models.IntegerField(default=1)),
                ('type', models.CharField(choices=[('Cu', 'Cute'), ('Co', 'Cool'), ('Pa', 'Passion'), ('Al', 'All')], max_length=50)),
                ('notes', models.IntegerField(default=100)),
                ('grade', models.CharField(choices=[('De', 'DEBUT'), ('Re', 'REGULAR'), ('Pr', 'PRO'), ('Ma', 'MASTER'), ('MP', 'MASTER PLUS')], max_length=50)),
            ],
        ),
    ]
