# Generated by Django 3.0 on 2020-01-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dereste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='grade',
            field=models.CharField(choices=[('De', 'DEBUT'), ('Re', 'REGULAR'), ('Pr', 'PRO'), ('Ma', 'MASTER'), ('MP', 'MASTER_PLUS'), ('LMP', 'Legend_MASTER_PLUS'), ('Fo', 'FORTE'), ('Pi', 'PIANO'), ('Li', 'LIGHT'), ('Ti', 'TRICK')], max_length=50),
        ),
    ]
