# Generated by Django 3.0.2 on 2020-02-07 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dereste', '0003_auto_20200126_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('perfect', models.IntegerField(default=0)),
                ('great', models.IntegerField(default=0)),
                ('nice', models.IntegerField(default=0)),
                ('bad', models.IntegerField(default=0)),
                ('miss', models.IntegerField(default=0)),
                ('result', models.CharField(choices=[('x', 'x'), ('C', 'C'), ('B', 'B'), ('A', 'A'), ('S', 'S')], default='x', max_length=4)),
                ('combo', models.IntegerField(default=0)),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dereste.Songs')),
            ],
        ),
    ]
